sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
cache: pip
install:
  - "travis_retry pip install tox-travis"
script:
  - tox
after_script:
  - cat .tox/$TOX_ENV/log/*.log